### ISSUE TITLE
Bug: proj:shape axis order should be (x, y) or (width, height)

### ISSUE THREAD

**Issue by JohanKJSchreurs** [VitoTAP/stac-catalog-builder#38]
## Bug:  `proj:shape` is filled in in the incorrect order: (Y,X) or (height, width)

According to the specification of the [Projection STAC extension](https://github.com/stac-extensions/projection) the axis order in the `proj:shape` field should be `(X, Y)` or in other words `(width, height)`.

But what we get from the Rasterio `dataset.shape`  is actually  `dataset.shape == (dataset.height, dataset.width))`

This is in fact logical for Rasterio because the axis order in NumPy is rows, column, which translates on a screen to "height (number of rows), then width (number of columns)", or in other words to "(Y, X)".
Also, this may be based on the conventions that GDAL follows.

So, to adhere to the specification we need to reverse the axis when we save this to proj:shape.

---

_Note: This was flagged because we had a similar issue with `proj:shape` in openEO, because GDAL / gdalinfo also uses the order (Y, X) / (height, width)._

---

Note: small code snippet to check the axis order:

```python

from pathlib import Path
import rasterio

def test_shape_axis_order(raster_file: Path):
    with rasterio.open(raster_file) as dataset:
        print(dataset.shape == (dataset.height, dataset.width)) 
        print(f"{dataset.shape=}")
        print(f"{dataset.width=}, {dataset.height=}")
```

**Comment by jdries** [comment]
@JohanKJSchreurs  I believe proj:shape is actually defined as being Y,X

**Comment by JohanKJSchreurs** [comment]
> @JohanKJSchreurs I believe proj:shape is actually defined as being Y,X

You are right. I should have looked it up more thoroughly before logging the issue.

Relevant part of the spec that confirms the prescribed order is Y, X :
https://github.com/stac-extensions/projection?tab=readme-ov-file#projshape
